#!/bin/bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lsh='ls -sh'
alias lm='ls -m'
alias lam='ls -Am'
alias nv='nvim'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias src='source'
alias sbrc='source ~/.bashrc'
alias py='python3'
alias httpp='http-server -p'
alias lbtr='libretranslate &'
alias sshd='/usr/sbin/sshd'
alias tcg='termux-clipboard-get'
alias tcs='termux-clipboard-set'
