#!/usr/bin/env bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lsh='ls -sh'
alias lm='ls -m'
alias lam='ls -Am'
alias nv='nvim'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias src='source'
alias sbrc='source ~/.bashrc'
alias py='python3'
alias dfur='df --output=used / | tail -n1'
alias gpush='git push'
alias gstat='git status'
alias gtag='git tag'
alias grbsi='git rebase -i'
alias grbsir='git rebase -i --root'
alias grbsc='git add * && git rebase --continue'
alias gdiff='git diff'
alias gdiffh='git diff HEAD'
alias httpp='http-server -p'
alias lbtr='libretranslate &'
alias yt-sub='yt-dlp --write-subs --sub-format vtt  --skip-download'
alias sshd='/usr/sbin/sshd'
alias ccp='termux-clipboard-set'
alias cpt='termux-clipboard-get'
