#!/usr/bin/env bash

shopt -s globstar

if [ -d "$HOME/.bashrc.d" ]; then
	for f in "$HOME/.bashrc.d/"*; do
		[ -r "$f" ] && source "$f"
	done
fi

if ! shopt -oq posix; then
	[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
	[ -f /etc/bash_completion ] && . /etc/bash_completion
fi

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

[ -f "${HOME}"/.config/broot/launcher/bash/br ] && source "${HOME}"/.config/broot/launcher/bash/br

[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"

command -v fzf >/dev/null 2>&1 && eval "$(fzf --bash)"

export MAMBA_ROOT_PREFIX="${HOME}/conda"
source "${HOME}/conda/etc/profile.d/conda.sh" 2>/dev/null || true
source "${HOME}/conda/etc/profile.d/mamba.sh" 2>/dev/null || true

[ -f "$HOME/.bashrc.overrides" ] && . "$HOME/.bashrc.overrides" || true
