#!/data/data/com.termux/files/usr/bin/bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lsh='ls -sh'
alias lm='ls -m'
alias lam='ls -Am'
alias nv='nvim'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias src='source'
alias sbrc='source ~/.bashrc'
alias py='python3'
alias dfur='df $(dirname "$PREFIX") | tail -n1 | awk '"'"'{print $3}'"'"
alias gpush='git push'
alias gstat='git status'
alias grbsi='git rebase -i'
alias gdfhd='git diff HEAD'
alias ping='/data/data/com.termux/files/usr/bin/ping'
alias httpp='http-server -p'
alias yt-sub='yt-dlp --write-subs --sub-format vtt  --skip-download'
alias ccp='termux-clipboard-set'
alias cpt='termux-clipboard-get'
