#!/bin/bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lsh='ls -sh'
alias lm='ls -m'
alias lam='ls -Am'
alias nv='nvim'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias src='source'
alias sbrc='source ~/.bashrc'
alias py='python3'
alias httpp='http-server -p'
alias lbtr='libretranslate &'
alias open-notebook-up='(cd ~/.open-notebook && docker compose up -d)'
alias open-notebook-stop='(cd ~/.open-notebook && docker compose stop)'
alias open-notebook-down='(cd ~/.open-notebook && docker compose down)'
alias stirlingpdf-up='(cd ~/stirlingpdf && docker compose up -d)'
alias stirlingpdf-stop='(cd ~/stirlingpdf && docker compose stop)'
alias stirlingpdf-down='(cd ~/stirlingpdf && docker compose down)'
alias litellm-up='(cd ~/.litellm && docker compose up -d)'
alias litellm-stop='(cd ~/.litellm && docker compose stop)'
alias litellm-down='(cd ~/.litellm && docker compose down)'
alias binance='/opt/Binance/binance --no-sandbox'
