#!/usr/bin/env bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lsh='ls -sh'
alias lm='ls -m'
alias lam='ls -Am'
alias nv='nvim'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias py='python3'
alias dfur='df --output=used / | tail -n1'
alias shch='shellcheck'
alias gpush='git push'
alias gstat='git status'
alias gtag='git tag'
alias grbsi='git rebase -i'
alias grbsir='git rebase -i --root'
alias grbsc='git add * && git rebase --continue'
alias gdiff='git diff'
alias gdiffh='git diff HEAD'
alias httpp='http-server -p'
alias lbtr='libretranslate &'
alias yt-sub='yt-dlp --write-subs --sub-format vtt  --skip-download'
alias typetype-up='(cd ~/typetype-stack && docker compose -f docker-compose.yml --env-file .env up)'
alias typetype-stop='(cd ~/typetype-stack && docker compose -f docker-compose.yml stop)'
alias typetype-down='(cd ~/typetype-stack && docker compose -f docker-compose.yml down)'
alias stirlingpdf-up='(cd ~/stirlingpdf && docker compose up -d)'
alias stirlingpdf-stop='(cd ~/stirlingpdf && docker compose stop)'
alias stirlingpdf-down='(cd ~/stirlingpdf && docker compose down)'
alias open-notebook-up='(cd ~/.open-notebook && docker compose up -d)'
alias open-notebook-stop='(cd ~/.open-notebook && docker compose stop)'
alias open-notebook-down='(cd ~/.open-notebook && docker compose down)'
alias litellm-up='(cd ~/.litellm && docker compose up -d)'
alias litellm-stop='(cd ~/.litellm && docker compose stop)'
alias litellm-down='(cd ~/.litellm && docker compose down)'
alias binance='/opt/Binance/binance --no-sandbox'
alias onlyoffice='desktopeditors'
alias ccp='wl-copy'
alias cpt='wl-paste'
alias dph='dolphin'
