#!/usr/bin/env bash

alias dfur='df --output=used / | tail -n1'
alias dfhur='df -h --output=used / | tail -n1'
alias typetype-up='(cd ~/typetype-stack && docker compose -f docker-compose.yml --env-file .env up)'
alias typetype-stop='(cd ~/typetype-stack && docker compose -f docker-compose.yml stop)'
alias typetype-down='(cd ~/typetype-stack && docker compose -f docker-compose.yml down)'
alias stirlingpdf-up='(cd ~/stirlingpdf && docker compose up -d)'
alias stirlingpdf-stop='(cd ~/stirlingpdf && docker compose stop)'
alias stirlingpdf-down='(cd ~/stirlingpdf && docker compose down)'
alias open-notebook-up='(cd ~/.open-notebook && docker compose up -d)'
alias open-notebook-stop='(cd ~/.open-notebook && docker compose stop)'
alias open-notebook-down='(cd ~/.open-notebook && docker compose down)'
alias litellm-up='(cd ~/.litellm && docker compose up -d)'
alias litellm-stop='(cd ~/.litellm && docker compose stop)'
alias litellm-down='(cd ~/.litellm && docker compose down)'
alias binance='/opt/Binance/binance --no-sandbox'
alias onlyoffice='desktopeditors'
alias dph='dolphin'
