#!/bin/bash

alias bottles='flatpak run com.usebottles.bottles'
alias bottles-cli='flatpak run --command=bottles-cli com.usebottles.bottles'
alias handbrake='flatpak run fr.handbrake.ghb'
alias handbrake-cli='flatpak run --command=HandBrakeCLI fr.handbrake.ghb'
alias enteauth='flatpak run io.ente.auth'
alias freetube='flatpak run io.freetubeapp.FreeTube'
alias brisk='flatpak run io.github.BrisklyDev.Brisk'
alias newsflash='flatpak run io.gitlab.news_flash.NewsFlash'
alias gimp='flatpak run org.gimp.GIMP'
alias simple-scan='flatpak run org.gnome.SimpleScan'
alias kdenlive='flatpak run org.kde.kdenlive'
alias krita='flatpak run org.kde.krita'
alias localsend='flatpak run org.localsend.localsend_app'
alias musescore='flatpak run org.musescore.MuseScore'
alias onlyoffice='flatpak run org.onlyoffice.desktopeditors'
alias vlc='flatpak run org.videolan.VLC'
