#!/bin/bash

alias joplin-desktop='$HOME/.joplin/Joplin.AppImage --no-sandbox'
alias bottles='flatpak run com.usebottles.bottles'
alias bottles-cli='flatpak run --command=bottles-cli com.usebottles.bottles'
alias handbrake='flatpak run fr.handbrake.ghb'
alias handbrakecli='flatpak run --command=HandBrakeCLI fr.handbrake.ghb'
alias freetube='flatpak run io.freetubeapp.FreeTube'
alias brisk='flatpak run io.github.BrisklyDev.Brisk'
alias gimp='flatpak run org.gimp.GIMP'
alias krita='flatpak run org.kde.krita'
alias musescore='flatpak run org.musescore.MuseScore'
alias onlyoffice='flatpak run org.onlyoffice.desktopeditors'
alias telegram='flatpak run org.telegram.desktop'
alias vlc='flatpak run org.videolan.VLC'
