#!/usr/bin/env bash

[ -f "$HOME/.bashrc.prepend" ] && . "$HOME/.bashrc.prepend" || true

if [ -d "$HOME/.bashrc.d" ]; then
	for f in "$HOME/.bashrc.d/"*; do
		[ -r "$f" ] && source "$f"
	done
fi

[ -f "$HOME/.bashrc.overrides" ] && . "$HOME/.bashrc.overrides" || true
